name: Trigger auto deployment for app-backend-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/app-backend-prod-AutoDeployTrigger-dfb1fb74-02a5-49a3-9853-9f1f15e95bb9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APPBACKENDPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPBACKENDPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPBACKENDPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.APPBACKENDPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPBACKENDPROD_REGISTRY_PASSWORD }}
          containerAppName: app-backend-prod
          resourceGroup: rg-ai-flashcards-prod
          imageToBuild: sanjaygeorge16/app-backend-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


